### ISSUE TITLE
Guide for setting up the shader

### ISSUE THREAD

**Issue by Festivize** [Festivize/Blender-miHoYo-Shaders#2]

**Comment by shruru** [comment]
Thanks. but if a video tutorial of this how to apply the shader to any blender object. would be GREAT. Thanks.

**Comment by Festivize** [comment]
> Thanks. but if a video tutorial of this how to apply the shader to any blender object. would be GREAT. Thanks.

I'll certainly be making a video tutorial setting up the shader for Genshin characters sometime soon - however I personally feel like a tutorial for any model would be overkill and unnecessary. There are just so many things that you have to make by yourself from lightmaps to vertex colors. I suggest that you just use another toon shader specifically made for custom character models, Ben Ayers' Genshin Impact shader from ArtStation comes to mind. With that said, I don't know if I misunderstood you or not but if you actually meant that, then no sadly I won't making a tutorial nor provide support for custom characters.

**Comment by Festivize** [comment]
We now have one! A huge thank you to [No_Tables](https://twitter.com/No_Tables) for making an easy to understand [tutorial](https://youtu.be/97G7LqFoTdY) showcasing the actual shader without any post-processing, and providing an in-depth overview as well.

Closing issue.
